package jpa.dao;

import java.util.List;

import jpa.entitymodels.Course;
import jpa.entitymodels.Student;

public interface StudentDAO {
	
	enum StudentSQL{
		get_All_Students("from Student S left join fetch S.sCourses "),
		get_Student_By_Email("from Student S left join fetch S.sCourses where S.sEmail = :sEmail");

		private final String query;
		
		//Enumeration constructor
		private StudentSQL(String query_string) {
			this.query = query_string;
		}
		
		public String getQuery() {
			return query;
		}
	}
	//Queries the student tables and returns all students records as Student objects
	//@return a  List<Student>
	public List<Student> getAllStudents();
	
	/**
	 * Queries students table for specific student email and
	 * returns Student object containing email specified
	 * @param id
	 * @return a Student object
	 */
	public Student getStudentByEmail(String sEmail);
	
 /**
  * @param sEmail
  * @param sPassword
  * @return  whether or not a student was found.
  */
	public boolean validateStudent(String sEmail,String sPassword);
	
	/**
	 * It checks in the join table (i.e. Student_Course) generated by JPA 
	 * to find if a Student with that Email is currently attending a Course with that ID.
	 * @param sEmail
	 * @param cId
	 */
	public void registerStudentToCourse(String sEmail, int cId);
	
	/**
	 * This method takes a Student’s Email as a parameter and would 
	 * find all the courses a student is registered for.
	 * @return a List Course
	 */	
	public List<Course> getStudentCourses(String sEmail);
	
	
}
